world:
  name: world
normalSpawn:
  x: -124.0
  y: 4.0
  z: -277.0
spawnRed:
  x: -128
  y: 6
  z: -330
spawnBlue:
  x: -144
  y: 6
  z: -332
bedRed:
  x: 108
  y: 5
  z: -332
bedBlue:
  x: -104
  y: 4
  z: -317
shopNames:
  0: Hauptshop
  1: Bloecke
  2: Schwerter
  3: Leder Ruestung
  4: Eisen Ruestung
  5: Essen
  6: Spezial
  7: Dies ist kein Shop
  8: Dies ist kein Shop
  9: Dies ist kein Shop
firstItem:
  item: Sandstone
  name: Bloecke
secondItem:
  item: Schwerter
  name: GOLD_SWORD
thirdItem:
  item: LEATHER_CHESTPLATE
  name: Leder Ruestung
fourthItem:
  item: IRON_CHESTPLATE
  name: Eisen Ruestung
fifthItem:
  item: COOKED_BEEF
  name: Essen
sixthItem:
  item: BEACON
  name: Spezial
seventhItem:
  item: AIR
  name: nothing
eighthItem:
  item: AIR
  name: nothing
ninthItem:
  item: Air
  name: nothing
shop1_first:
  amount: 8
  price: 2
  priceItem: CLAY_BRICK
  item: SANDSTONE
  name: nothing
  dura: 100
shop1_second:
  amount: 16
  price: 8
  priceItem: CLAY_BRICK
  item: SANDSTONE
  name: nothing
  dura: 100
shop1_third:
  amount: 8
  price: 2
  priceItem: IRON_BAR 
  item: END_STONE
  name: nothing
  dura: 100
shop1_fourth:
  amount: 1
  price: 0
  priceItem: AIR
  item: AIR
  name: nothing
  dura: 30
shop1_fifth:
  amount: 1
  price: 10
  priceItem: CLAY_BRICK
  item: WOODEN_PICKAXE
  name: nothing
  dura: 50
shop1_sixth:
  amount: 1
  price: 20
  priceItem:
    item: WOODEN_PICKAXE
  name: nothing
  dura: 100
shop1_seventh:
  amount: 1
  price: 1
  priceItem: IRON_BAR
  item: STONE_PICKAXE
  name: nothing
  dura: 100
shop1_eighth:
  amount: 1
  price: 3
  priceItem: IRON_BAR
  item: IRON_PICKAXE
  name: nothing
  dura: 100
shop1_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop2_first:
  amount: 1
  price: 15
  priceItem: 
  item: BOW
  name: nothing
  dura: 50
shop2_second:
  amount: 1
  price: 100
  priceItem:
  item: BOW
  name: nothing
  dura: 1
shop2_third:
  amount: 12
  price: 120
  priceItem:
  item: ARROW
  name: nothing
  dura: 100
shop2_fourth:
  amount: 24
  price: 200
  priceItem:
  item: ARROW
  name: nothing
  dura: 100
shop2_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop2_sixth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop2_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop2_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop2_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop3_first:
  amount: 1
  price: 6
  priceItem:
  item: LEATHER_HELMET
  name: nothing
  dura: 100
shop3_second:
  amount: 1
  price: 10
  priceItem:
  item: LEATHER_CHESTPLATE
  name: nothing
  dura: 100
shop3_third:
  amount: 1
  price: 8
  priceItem:
  item: LEATHER_LEGGINGS
  name: nothing
  dura: 100
shop3_fourth:
  amount: 1
  price: 7
  priceItem:
  item: LEATHER_BOOTS
  name: nothing
  dura: 100
shop3_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop3_sixth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop3_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop3_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop3_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop4_first:
  amount: 1
  price: 15
  priceItem:
  item: GOLD_HELMET
  name: nothing
  dura: 50
shop4_second:
  amount: 1
  price: 20
  priceItem:
  item: GOLD_CHESTPLATE
  name: nothing
  dura: 50
shop4_third:
  amount: 1
  price: 18
  priceItem:
  item: GOLD_LEGGINGS
  name: nothing
  dura: 50
shop4_fourth:
  amount: 1
  price: 16
  priceItem:
  item: GOLD_BOOTS
  name: nothing
  dura: 50
shop4_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop4_sixth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop4_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop4_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop4_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop5_first:
  amount: 1
  price: 28
  priceItem:
  item: CHAINMAIL_HELMET
  name: nothing
  dura: 30
shop5_second:
  amount: 1
  price: 40
  priceItem:
  item: CHAINMAIL_CHESTPLATE
  name: nothing
  dura: 30
shop5_third:
  amount: 1
  price: 35
  priceItem:
  item: CHAINMAIL_LEGGINGS
  name: nothing
  dura: 30
shop5_fourth:
  amount: 1
  price: 30
  priceItem:
  item: CHAINMAIL_BOOTS
  name: nothing
  dura: 30
shop5_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop5_sixth:
  amount: 1
  price: 10000
  item: AIR
  priceItem:
  name: nothing
  dura: 100
shop5_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop5_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop5_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop6_first:
  amount: 1
  price: 50
  priceItem:
  item: IRON_HELMET
  name: nothing
  dura: 40
shop6_second:
  amount: 1
  price: 65
  priceItem:
  item: IRON_CHESTPLATE
  name: nothing
  dura: 40
shop6_third:
  amount: 1
  price: 60
  priceItem:
  item: IRON_LEGGINGS
  name: nothing
  dura: 40
shop6_fourth:
  amount: 1
  price: 55
  priceItem:
  item: IRON_BOOTS
  name: nothing
  dura: 40
shop6_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop6_sixth:
  amount: 1
  price: 85
  priceItem:
  item: IRON_HELMET
  name: nothing
  dura: 60
shop6_seventh:
  amount: 1
  price: 100
  priceItem:
  item: IRON_CHESTPLATE
  name: nothing
  dura: 60
shop6_eighth:
  amount: 1
  price: 95
  priceItem:
  item: IRON_LEGGINGS
  name: nothing
  dura: 60
shop6_ninth:
  amount: 1
  price: 90
  priceItem:
  item: IRON_BOOTS
  name: nothing
  dura: 60
shop7_first:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_second:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_third:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_fourth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_sixth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop7_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_first:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_second:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_third:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_fourth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_sixth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop8_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_first:
  amount: 1
  price: 10000
  priceItem:
  item: WOOL
  name: nothing
  dura: 100
shop9_second:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_third:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_fourth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_fifth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_sixth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_seventh:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_eighth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
shop9_ninth:
  amount: 1
  price: 10000
  priceItem:
  item: AIR
  name: nothing
  dura: 100
