Lobby:
  name: world
normalSpawn:
  x: -124.0
  y: 4.0
  z: -277.0
spawnRed:
  x: -3
  y: 53
  z: -63
spawnBlue:
  x: -1
  y: 53
  z: 61
bedRed:
  x: -2
  y: 53
  z: -62
bedBlue:
  x: -2
  y: 53
  z: 60
RushWorld:
  name: rushMap
WLPLayers:
  1: recklessGreed_
  2: ZanderLP
  3: Logifex
  4: Skyi
  5: aysli